name: Terraform Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionsTerraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ">= 1.11.4"

      - name: Initialize Terraform
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"
        working-directory: ./

      - name: Format and Validate Terraform
        id: fmt_validate
        run: terraform validate
        working-directory: ./

      - name: Generate Terraform Plan
        id: plan
        run: terraform plan -no-color -lock=false
        working-directory: ./

      - name: Create Plan Output Markdown
        id: plan_report
        run: |
          echo "#### Terraform Plan Output" >> plan.md
          echo "```terraform" >> plan.md
          echo "$(terraform plan -no-color)" >> plan.md
          echo "```" >> plan.md
        working-directory: ./

      - name: Comment Plan to Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          PLAN: "${{ steps.plan_report.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('./plan.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: planOutput
            });

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve -lock=false
        working-directory: ./
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
